### ISSUE TITLE
Does not work as description.

### ISSUE THREAD

**Issue by kencom999** [WadieBenabdouh/AutoClipboardCleaner#2]
Your script does not clear the Clipboard, what it does is copying "nothing", which overwrites what you copied. If you check your clipboard with the "Windows Logo + V" button, you can still see your copy history with the newly copied nothing.

**Comment by WadieBenabdouh** [comment]
Yeah actually I saw someone on YouTube that shared this command line and I though of turning it into a batch file, it does not clean your clipboard but I find it useful when messing with shortcut icons on my desktop, such as copying files or icons etc...
it does not work with text though.
